export default {
    index: 'Act 01 - The Pact',
    discovery: 'Discovery',
    beginning: 'Beginning',
    blowup: 'Blow Up',
    themeeting: 'The Meeting',
    memories: 'Memories',
    hatred: 'Hatred',
    rescue: 'Rescue',
    breakthrough: 'Breakthrough',
    adjudication: 'Adjudication',
    detection: 'Detection',
    contact: 'Contact',
    welcoming: 'Welcoming',
    //pactchapter: 'The Pact',
  }