export default function robots() {
    return {
        rules: 
        [
            {// known AI Bots
                userAgent: 
                    [ 
                        'AI2Bot',
                        'Ai2Bot-Dolma',
                        'Amazonbot',
                        'anthropic-ai',
                        'Applebot',
                        'Applebot-Extended',
                        'Bytespider',
                        'CCBot',
                        'ChatGPT-User',
                        'Claude-Web',
                        'ClaudeBot',
                        'cohere-ai',
                        'Diffbot',
                        'DuckAssistBot',
                        'FacebookBot',
                        'FriendlyCrawler',
                        'Google-Extended',
                        'GoogleOther',
                        'GoogleOther-Image',
                        'GoogleOther-Video',
                        'GPTBot',
                        'iaskspider/2.0',
                        'ICC-Crawler',
                        'ImagesiftBot',
                        'img2dataset',
                        'ISSCyberRiskCrawler',
                        'Kangaroo Bot',
                        'Meta-ExternalAgent',
                        'Meta-ExternalFetcher',
                        'OAI-SearchBot',
                        'omgili',
                        'omgilibot',
                        'PanguBot',
                        'PerplexityBot',
                        'PetalBot',
                        'Scrapy',
                        'Sidetrade indexer bot',
                        'Timpibot',
                        'VelenPublicWebCrawler',
                        'Webzio-Extended',
                        'YouBot'
                    ],
                disallow: '/'
            },
            {// known bad actor bots
                userAgent: 
                    [
                        '11A465',
                        'Ahrefs',
                        'ArchiveBot',
                        'AspiegelBot',
                        'Baiduspider',
                        'bingbot',
                        'BLEXBot',
                        'crawler4j',
                        'Csnibot',
                        'Curebot',
                        'Daum',
                        'Detectify',
                        'DotBot',
                        'Fuzz Faster U Fool',
                        'gobuster',
                        'Grapeshot',
                        'heritrix',
                        'HTTrack',
                        'ICC-Crawler',
                        'KauaiBot',
                        'Kinza',
                        'LieBaoFast',
                        'Linespider',
                        'Linguee',
                        'LinuxGetUrl',
                        'LMY47V',
                        'Mail.RU_Bot',
                        'MauiBot',
                        'Mb2345Browser',
                        'MegaIndex',
                        'MicroMessenger',
                        'MJ12bot',
                        'Monsidobot',
                        'Mozlila',
                        'MQQBrowser',
                        'Neevabot',
                        'nettle',
                        'Orbbot',
                        'PageFreezer',
                        'PetalBot',
                        'PiplBot',
                        'Riddler',
                        'RustBot',
                        'Scrapy',
                        'Screaming Frog',
                        'Search365bot',
                        'SearchBlox',
                        'Seekport',
                        'SemanticScholarBot',
                        'SemrushBot',
                        'SEOkicks',
                        'serpstatbot',
                        'Siteimprove.com',
                        'SiteSucker',
                        'Sogou web spider',
                        'trendictionbot',
                        'trendkite-akashic-crawler',
                        'Turnitin',
                        'UCBrowser',
                        'weborama-fetcher',
                        'Vagabondo',
                        'VelenPublicWebCrawler',
                        'YandexBot',
                        'YisouSpider',
                        'ZoominfoBot'
                    ],
                    disallow: '/'
            }
        ],
      sitemap: 'https://last-contact.net/sitemap.xml',
    }
  }